"""任务胶水：拉取沪深300历史成分股 + 全成分日 K 线，落库到本地。

编排顺序：
1. get_csi300_constituents 取历史成分 membership（默认每年 1/7 月查询）。
2. 取全部历史成分并集 + 000300.SH 指数作为标的池。
3. fetch_kline 逐标的复用 Vibe-Trading 数据层抓日 K，落 parquet。
4. 写 bridge_config.yaml 片段（可并入 ~/.vibe-trading/data-bridge/config.yaml）
   和 manifest.json 覆盖率报告。

用法（建议在 vibe-trading-src 仓库根目录用 venv python 运行）：
    E:\\gitCloneProgram\\vibe-trading-src\\.venv\\Scripts\\python.exe agent/scripts/run/run_fetch_csi300_kline.py --start-date 2020-01-01 --end-date 2026-12-31 --out-dir C:/tmp/csi300

默认输出目录：C:\\Users\\<user>\\.vibe-trading\\data-bridge\\csi300。
--append 会把增量模式透传给 fetch_kline：已有 parquet 的标只补头尾缺口。
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "lib"))

from fetch_kline import fetch_kline  # noqa: E402  # pyright: ignore[reportMissingImports]
from get_csi300_constituents import get_csi300_constituents  # noqa: E402  # pyright: ignore[reportMissingImports]

logger = logging.getLogger(__name__)


def _build_bridge_config(out_dir: Path, saved: dict[str, int]) -> Path:
    """生成 data-bridge config.yaml 片段：已成功落盘的标的 -> parquet 路径。"""
    lines = [
        "# Generated by run_fetch_csi300_kline.py - merge this block into",
        "# ~/.vibe-trading/data-bridge/config.yaml, then use local:<code> in prompts.",
        "sources:",
    ]
    for code in sorted(saved):
        path = (out_dir / "kline" / f"{code}.parquet").as_posix()
        lines.append(f'  - symbol: "{code}"')
        lines.append("    type: parquet")
        lines.append(f'    path: "{path}"')
    config_path = out_dir / "bridge_config.yaml"
    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("bridge_config.yaml 片段已写入 %s", config_path)
    return config_path


def run_fetch_csi300(
    start_date: str,
    end_date: str,
    *,
    index: str = "399300.SZ",
    out_dir: str | Path,
    source: str = "auto",
    interval: str = "1D",
    snapshot_dates: list[str] | None = None,
    sleep_seconds: float = 0.2,
    max_retries: int = 3,
    fallback_timeout: float = 30.0,
    limit_codes: int = 0,
    append: bool = False,
) -> dict:
    """执行完整子任务并返回覆盖率报告。"""
    out_root = Path(out_dir)
    out_root.mkdir(parents=True, exist_ok=True)

    logger.info("步骤 1/3：抓取历史成分 membership")
    membership = get_csi300_constituents(
        start_date,
        end_date,
        index=index,
        out_dir=out_root,
        snapshot_dates=snapshot_dates,
        sleep_seconds=sleep_seconds,
        max_retries=max_retries,
        fallback_timeout=fallback_timeout,
    )
    if membership.df.empty:
        raise RuntimeError("成分股 membership 为空，无法继续抓 K 线")

    unique_codes = sorted(membership.df["code"].unique())
    universe = unique_codes + ["000300.SH"] if "000300.SH" not in unique_codes else unique_codes
    if limit_codes > 0:
        benchmark_codes = [c for c in universe if c == "000300.SH"]
        universe = sorted(set(unique_codes[:limit_codes] + benchmark_codes))
        logger.info(
            "联调/分批模式：仅抓前 %d 只成分，实际 universe=%d",
            limit_codes, len(universe),
        )
    logger.info(
        "步骤 2/3：标的池确定 unique_constituents=%d benchmark=000300.SH total=%d",
        len(unique_codes), len(universe),
    )

    logger.info("步骤 3/3：抓取日 K 线并落库 (append=%s)", append)
    fetch_result = fetch_kline(
        universe,
        start_date,
        end_date,
        out_root,
        source=source,
        interval=interval,
        append=append,
    )

    bridge_config = _build_bridge_config(out_root, fetch_result.saved)

    snapshot_count = int(membership.df["update_date"].nunique())
    report = {
        "task": "fetch_csi300_kline",
        "created_at": datetime.now(timezone.utc).isoformat(),
        "index": index,
        "start_date": start_date,
        "end_date": end_date,
        "interval": interval,
        "source": source,
        "append": append,
        "snapshot_count": snapshot_count,
        "unique_constituents": len(unique_codes),
        "codes_requested": len(universe),
        "codes_saved": len(fetch_result.saved),
        "codes_failed": len(fetch_result.failed),
        "codes_already_covered": len(fetch_result.already_covered),
        "codes_gap_skipped": len(fetch_result.gap_skipped),
        "gap_skipped": sorted(fetch_result.gap_skipped),
        "failed_codes": sorted(fetch_result.failed),
        "effective_sources": fetch_result.effective_sources,
        "survivorship_bias_free": True,
        "membership_files": [
            str(membership.membership_parquet),
            str(membership.membership_csv),
            str(membership.snapshots_json),
        ],
        "bridge_config": str(bridge_config),
        "kline_dir": str(out_root / "kline"),
        "warnings": membership.warnings,
    }

    manifest_path = out_root / "manifest.json"
    manifest_path.write_text(
        json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    logger.info("manifest 已写入 %s", manifest_path)
    logger.info(
        "覆盖率报告: snapshots=%d constituents=%d requested=%d saved=%d already=%d failed=%d gap_skipped=%d sources=%s",
        snapshot_count, len(unique_codes), len(universe),
        len(fetch_result.saved), len(fetch_result.already_covered), len(fetch_result.failed), len(fetch_result.gap_skipped),
        fetch_result.effective_sources,
    )
    if fetch_result.failed:
        logger.warning("缺失标的 %d 个: %s", len(fetch_result.failed), fetch_result.failed)
    if fetch_result.gap_skipped:
        logger.warning("缺口跳过标的 %d 个: %s", len(fetch_result.gap_skipped), fetch_result.gap_skipped)
    return report


def main() -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )
    default_out = str(Path.home() / ".vibe-trading" / "data-bridge" / "csi300")
    parser = argparse.ArgumentParser(description="拉取沪深300成分股日 K 落库")
    parser.add_argument("--start-date", default="2020-01-01", help="区间起始日")
    parser.add_argument("--end-date", default="2026-12-31", help="区间结束日")
    parser.add_argument("--index", default="399300.SZ", help="成分指数代码")
    parser.add_argument("--out-dir", default=default_out, help="输出目录")
    parser.add_argument("--source", default="auto", help="K 线数据源，默认 auto")
    parser.add_argument("--interval", default="1D", help="K 线周期，默认 1D")
    parser.add_argument("--snapshot-dates", help="覆盖成分查询日，逗号分隔")
    parser.add_argument("--sleep", type=float, default=0.2, help="查询间隔秒")
    parser.add_argument("--max-retries", type=int, default=3, help="最大重试次数")
    parser.add_argument("--fallback-timeout", type=float, default=30.0, help="兜底超时秒")
    parser.add_argument("--limit-codes", type=int, default=0, help="只抓前 N 只成分（0=全量，联调/分批用）")
    parser.add_argument("--append", action="store_true", help="增量模式：已有 parquet 的标的只补头尾缺口")
    args = parser.parse_args()

    snapshot_dates = None
    if args.snapshot_dates:
        snapshot_dates = [d.strip() for d in args.snapshot_dates.split(",") if d.strip()]

    report = run_fetch_csi300(
        args.start_date,
        args.end_date,
        index=args.index,
        out_dir=args.out_dir,
        source=args.source,
        interval=args.interval,
        snapshot_dates=snapshot_dates,
        sleep_seconds=args.sleep,
        max_retries=args.max_retries,
        fallback_timeout=args.fallback_timeout,
        limit_codes=args.limit_codes,
        append=args.append,
    )
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 0 if report["codes_saved"] > 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
